# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='street_address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
