# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 20:00
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170210_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(max_length=2, validators=[core.models.validate_state]),
        ),
    ]
