# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170213_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 2, 13, 20, 57, 17, 121825, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 2, 13, 20, 57, 34, 737825, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
