# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170213_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
