# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_provider_owner'),
    ]

    operations = [
    ]
